schema_version = "1.0.0"

id = "my_best_pie_menu_ever"
version = "2.9.0"
name = "My Best Pie Menu Ever"
tagline = "Quick access to the functions you need"
maintainer = "emptybraces <motose6@gmail.com>"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://emptybraces.github.io"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["3D View", "User Interface"]

blender_version_min = "4.3.0"
## Optional: Blender version that the extension does not support, earlier versions are supported.
## This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Import/export FBX from/to disk"


# ---------------------------
# v2.9.0
# - Blender5.0対応。
# - [WeightPaint, Edit] 選択した頂点が所属する頂点グループを選択できるポップアップ機能。(Inspect Selected Verts)
# v2.8.1
# - [ModeHistory] 横幅が短いのでモード名を一部短縮。
# v2.8.0
# - [ModeHistory] パイメニュー左側にモード選択（＋オブジェクト選択）履歴ポップオーバーを追加。
# - [WeightPaint] ウェイト設定/削除機能に非選択頂点を対象にするオプションを追加。
# - [WeightPaint] 左、または右のボーンだけ非表示にする機能(Hide L/R Bones)を追加。
# - [WeightPaint] 選択頂点から拡大していくグラデーションウェイト機能(Gradient Weight Expand)を追加。
# - [WeightPaint] 選択中のポーズボーンのミラーボーンを選択する機能を追加。
# - [WeightPaint] ポーズボーンのミラーを設定項目を追加。
# - [Utility] アクティブオブジェクトカラムのレイアウト整理。
# - [Utility] アクティブな各データ(VertexGroup, ShapeKey, UV)を選択できるプルダウンリストを追加。
# - [Utility] リンクされたArmatureのアクションスロットを追加。
# - [Utility] シェイプキーのアクティブ状態と全シェイプキーの状態の保存／復元処理を追加。
# - [Utility] ExportARP実行時、対象オブジェクトをリストから選択して実行できるように修正。
# - [Bugfix] 各ペイントモードでのブラーブラシの取得が不安定なバグを修正。
# - [Bugfix] ウェイトペイントモードでウェイト済み頂点を選択する機能がゼロウェイト頂点も選択してしまう。
# v2.7.1
# - [Bugfix] スカルプトブラシのフィルタモードが機能していない。
# - ミニマムバージョンを4.3.0にアップ。
# v2.7.0
# - [Pose] Auto-Rig Pro　IKFKスイッチ機能を更新。
# - [Utility] アクティブコレクションの表示非表示ボタンを追加。
# - [Utility] 選択オブジェクトを一つ一つ表示する機能を追加。
# - [EditMesh] ゴースト表示機能にアルファカラーフィールドを追加。
# - [EditMesh] 頂点融解のミラー機能の追加。
# - [EditMesh] 頂点マージのミラー機能の追加。
# - [EditMesh] エッジループ(マージ)のミラー機能の追加。
# - [EditMesh] 頂点連結のミラー機能の追加。
# - [ImagePaint] シフトキーブラシのエラー解消&登録処理の追加。
# - [SwitchObjectData] Gキーでパネルを移動できるようにした。
# - [SwitchObjectData] 対象データ選択時、自動的に最適なモードに切り替わるようにした。
# - [Bugfix] SwitchObjectData項目選択ロジックが不安定。
# - [Bugfix] SwitchObjectData/Blendshapeで、頻繁に変更するとクラッシュする。
# - [Bugfix] SwitchObjectData/VertexGroupで、アクティブなVertexGroupがないときリストが非表示になる。
# - [Bugfix] モード変更ボタンのテキスト見切れ。
# - [Bugfix] ウェイトペイント時のボーン非表示処理が動かない
# - [Bugfix] パイメニューが閉じない、または点滅するバグを修正
# v2.6.0
# - [Object/EditMesh] ゴースト表示機能を実装。
# - [EditMesh] 頂点固定機能を実装。
# - [EditMesh] エッジリングのセンタリング機能を実装。
# - [EditMesh] クリースレイヤ、ベベルウェイトレイヤのボタンをスライダー化。
# - [Utility] ビューポートカメラ履歴アニメを滑らかにした。
# - [Fix] 第2言語に切り替えたときに「新規データ」がオンになってしまっていたので常にオフするように修正。
# - [Fix] blender4.4でWeightPaint,Sculptパイメニューを表示するとエラーが発生する。
# v2.5.0
# - [Weight] ウェイトが設定されている頂点以外をマスクするボタンを追加。
# - [EditMesh] "Grow Edge Ring Selection"を追加。
# - [Bugfix] "Generate bones along selected edges"のRedoパネルが表示されなくなってしまったため対応。
# v2.4.0
# - [Utility] 3DカーソルのX/Y/Z値を0にするボタンを追加。
# - [Weight] 左クリックしたときにボーンを非表示にするトグルを追加。
# - [Weight] ウェイトが設定されている頂点のみマスクするボタンを追加。
# v2.3.0
# - [EditMesh] 3Dカーソル基準に頂点位置をミラーリングする機能を追加。
# - [Utility] アニメーション速度フィールドを追加、アニメフレーム同期ボタンはアニメーション速度を参照するように修正。
# - [Utility, Pose] ボーンコレクションの表示機能を追加。
# - [Bugfix] カーソルがメニューを開いた位置から十分な距離に離れたときメニューを自動で閉じる機能を削除。
# v2.2.0
# - [Switch Object Data] アクティブオブジェクトの頂点グループ、シェイプキー、UVMap、カラー頂点情報を高速に切り替える機能を追加。
# - [Edit] 選択している頂点をアクティブな頂点グループに追加/削除するボタンを追加し、整理。
# - [修正] レイアウト配置調整。
# v2.1.1
# - [修正] ビューポートカメラ復元時にエラー。
# - [修正] ボーン選択頂点グループミラー時にエラー。
# v2.1.0
# - [ImagePaint] ブラシ、ブレンドフィルターモードを追加。
# - [Sculpt] ブラシフィルターモードを追加。
# - [Weight] 拡張ウェイト設定/削除ボタンを追加。
# - [修正] テクスチャペイントのシフトキー＋LMB処理が機能していなかった。
# - [修正] ウェイトペイントブラーブラシが読み込めずエラー。
# - [修正] スカルプトスムーズブラシが読み込めずエラー。
# - [修正] アクティブオブジェクトがないときにパイメニューを開くとエラー。
# - [修正] ウェイトペイントモードからウェイトペイント+アーマチュア選択ボタンが機能していなかった。
# - [修正] ウェイトペイントブラシのパラメータ設定が機能していなかった。
#
# v2.0.0 
# - [パイメニュー]Blender v4.3に対応
# - [パイメニュー]シフトキーを押しながらボタンクリックでパイメニューを閉じないようにした。
# - [Mode]スカルプトモードへ移行と同時に選択頂点を面セットに設定するボタンを追加。
# - [Utility]シェーディングモード、オブジェクトカラーを追加。
# - [Utility]ビューポートカメラTransformの保存／復元のアップデート、アニメ機能追加。
# - [Utility]アニメーションフレームの開始／終了／同期ボタン追加。
# - [Utility]Armatureボーンとアニメーションフレームの同時リセットボタンを追加。
# - [EditMesh]AlignViewToEdgeNormalSide機能を追加。
# - [EditMesh]表示、非表示の拡張ボタンを追加。
# - [Sculpt]ブラシアイコン表示。(v4.2のみ)
# - [Sculpt]選択頂点によるFaceSet設定オペレータを追加。
# - [Weight]頂点グループミラー生成（トポロジー）ボタンを追加。
# - [UV]ユーティリティペインを更新。
# - [修正]イメージペイントブラシ共通パラメータ切替の不具合を修正。
# - [修正]頂点グループ選択処理が遅い不具合を修正。
# - [修正]頂点グループ選択処理時に辺・面モードだと選択されない不具合を修正。
# - [修正]頂点グループがたくさんあるときリストアイテムが極端に小さくなる不具合を修正。
# - [修正]スカルプトモードのワイヤーフレーム自動オンがBlender起動時に働かない不具合を修正。
# - [修正]オブジェクトのワイヤフレーム表示トグルが操作できなくなってしまう不具合を修正。
# - [修正]頂点選択せずにスカルプトマスクボタンでモード遷移するとエラーが発生するバグを修正。
# - [修正]multiresモディファイア時にスカルプトマスクボタンで遷移してもマスクが有効にならない不具合を修正。（仕様によりモディファイア有効状態でのマスクにはできない。）
#
# v1.5.0 - ディレクトリオープンボタン追加。頂点グループオーバーレイボタンを追加。先頭にアンダースコアが付いているブラシ名に変更するとエラーが発生するバグを修正。スカルプトモード変更時に自動でワイヤーフレーム化するオプションを追加。頂点複製ミラーした頂点に各情報を全てコピーするように修正。UVMap選択リスト追加。Sculpt＋マスク遷移ボタン。UVEditorパイメニュー更新。直前のモード変更ボタンを追加。ペイント：共通のサイズを使用ショートカット。
# v1.4.1 - 頂点複製ミラーのバグ修正。ライセンスをGPL3.0に変更。
# v1.4.0 - 頂点複製ミラーを追加。未使用頂点グループの一括削除処理を追加。頂点グループ選択パネルに頂点数を表示。修正：ARPFKIP切り替えショートカットが動作していなかった。ウェイトペイントメニューにぼかしブラシ強さを常時表示。選択辺に沿ってボーン生成する機能を追加。スカルプトモードで選択した頂点をマスクする機能を追加。選択ツール切り替えボタン追加。頂点グループ選択パネル内にCLEAR SELECTIONボタンを追加。
# -
# v1.3.8 - uesrキーマップスコープに'3D View'がないとき、エラーが発生するバグを修正。
# v1.3.7 - カラーパレットアクセス。3Dカーソルの選択頂点垂直ベクトル移動。
# v1.3.6 - 1.3.5のバグ修正。
# v1.3.5 - ビューポートカメラの位置角度保存復元ボタン。Pivotセット、シェーディングセットボタン説明追加。クリース編集ボタン。孤立を削除ボタン追加。ブラシ蓄積プロパティ追加。Smoothスカルプトブラシ強さの変更。頂点グループ選択処理をその場で繰り返し設定できるように修正。頂点クリース追加。辺クリース修正。
# v1.3.4 - 頂点グループ追加ボタン。頂点グループ選択ボタン。頂点マージボタンの修正。３Dカーソルをビュー平面上移動。選択オブジェクトのPRSコピー。
# v1.3.3 - フォルダ名の変更
# v1.3.2 - blender_manifest更新
# v1.3.1 - BlenderExtension
# ---------------------------
